<a href="https://colab.research.google.com/github/Meowmixforme/OH-Deer/blob/main/Notebooks/01_Red_Deer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First let's import the database and take a look at it's structure

In [1]:
import pandas as pd

df = pd.read_csv("records-2025-12-28.csv")

df.head()
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28964 entries, 0 to 28963
Data columns (total 54 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   NBN Atlas record ID                 28964 non-null  object
 1   Occurrence ID                       28964 non-null  object
 2   Licence                             28964 non-null  object
 3   rightsHolder                        28465 non-null  object
 4   Scientific name                     28964 non-null  object
 5   Taxon author                        28964 non-null  object
 6   Name qualifier                      0 non-null      float64
 7   Common name                         28964 non-null  object
 8   Species ID (TVK)                    28964 non-null  object
 9   Taxon Rank                          28964 non-null  object
 10  Occurrence status                   28964 non-null  object
 11  Event Date                          23444 non-null  object
 12  Day                                 20359 non-null  float64
 13  Month                               22583 non-null  float64
 14  Year                                28455 non-null  float64
 15  End date                            3085 non-null   object
 16  Locality                            20721 non-null  object
 17  Grid reference                      28609 non-null  object
 18  Latitude (WGS84)                    28706 non-null  float64
 19  Longitude (WGS84)                   28706 non-null  float64
 20  Coordinate Uncertainty (m)          28612 non-null  float64
 21  verbatimDepth                       0 non-null      float64
 22  Recorder                            15269 non-null  object
 23  Determiner                          6837 non-null   object
 24  Individual count                    13303 non-null  float64
 25  Abundance                           938 non-null    object
 26  Abundance scale                     41 non-null     object
 27  Organism scope                      0 non-null      float64
 28  Organism remarks                    9413 non-null   object
 29  Sex                                 1023 non-null   object
 30  Life stage                          1140 non-null   object
 31  Occurrence remarks                  4545 non-null   object
 32  Identification verification status  28964 non-null  object
 33  Basis of Record                     28964 non-null  object
 34  Survey key                          25545 non-null  object
 35  Dataset name                        28964 non-null  object
 36  Dataset ID                          28964 non-null  object
 37  Data provider                       28964 non-null  object
 38  Data provider ID                    28964 non-null  object
 39  Institution code                    17604 non-null  object
 40  Kingdom                             28964 non-null  object
 41  Phylum                              28964 non-null  object
 42  Class                               28964 non-null  object
 43  Order                               28964 non-null  object
 44  Family                              28964 non-null  object
 45  Genus                               28964 non-null  object
 46  OSGR 100km                          28601 non-null  object
 47  OSGR 10km                           28576 non-null  object
 48  OSGR 2km                            22188 non-null  object
 49  OSGR 1km                            21463 non-null  object
 50  Country                             28957 non-null  object
 51  State/Province                      28866 non-null  object
 52  Vitality                            3470 non-null   object
 53  Public resolution (m)               7 non-null      float64
dtypes: float64(11), object(43)
memory usage: 11.9+ MB

,NBN Atlas record ID,Occurrence ID,Licence,rightsHolder,Scientific name,Taxon author,Name qualifier,Common name,Species ID (TVK),Taxon Rank,...,Family,Genus,OSGR 100km,OSGR 10km,OSGR 2km,OSGR 1km,Country,State/Province,Vitality,Public resolution (m)
count,28964,28964,28964,28465,28964,28964,0.0,28964,28964,28964,...,28964,28964,28601,28576,22188,21463,28957,28866,3470,7.0
unique,28964,28924,4,120,1,1,NaN,1,1,1,...,1,1,48,1560,4768,6971,2,4,5,NaN
top,ffff73d1-3181-4983-b2c6-153772b6640f,24995634,CC-BY-NC,North-East Scotland Biological Records Centre,Cervus elaphus,"Linnaeus, 1758",NaN,Red Deer,NBNSYS0000005143,species,...,Cervidae,Cervus,NN,NJ01,SK53J,SK5339,United Kingdom of Great Britain and Northern I...,Scotland,alive,NaN
freq,1,2,17102,8298,28964,28964,NaN,28964,28964,28964,...,28964,28964,4161,1815,484,398,28954,19432,2651,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0

There are 28,964 rows and from a visual inspection we can see that:

- around 5,500 rows have no Event Date
- around 250 rows have no coordinates
- some records span date ranges
- some are duplicates from multiple datasets

First let's filter the record to only include valid spatial and temporal records.

In [2]:
df = pd.read_csv("records-2025-12-28.csv")

# Parse dates
df['Event Date'] = pd.to_datetime(df['Event Date'], errors='coerce')

# Keep only rows with usable coordinates AND a valid date
df_clean = df.dropna(subset=['Latitude (WGS84)', 'Longitude (WGS84)', 'Event Date'])

len(df_clean)

23422

Now we have 23422 records we should standardise column names

In [3]:
df_clean = df_clean.rename(columns={
    'Latitude (WGS84)': 'lat',
    'Longitude (WGS84)': 'lon',
    'Coordinate Uncertainty (m)': 'uncertainty',
    'Event Date': 'date',
    'Scientific name': 'scientific_name',
    'Common name': 'common_name'
})

Checking the count by year

In [6]:
pd.set_option('display.max_rows', None)
df_clean['year'].value_counts().sort_index()

year
1705       1
1736     135
1829       1
1830       1
1860       7
1880       1
1888       1
1900       2
1905      24
1909       5
1910       1
1915       1
1921       1
1930       1
1935       5
1938       1
1939       2
1940       2
1941       1
1942       2
1943       2
1944       7
1946       1
1956       1
1957       3
1958       8
1960      35
1961       2
1962       1
1963       1
1964       4
1965      28
1966      24
1967      26
1968      69
1969      85
1970     521
1971      46
1972      32
1973      20
1974       3
1975      24
1976      34
1977      38
1978      33
1979      51
1980      56
1981      47
1982      56
1983      44
1984      58
1985      53
1986      57
1987      57
1988      42
1989      41
1990     783
1991      56
1992      41
1993      89
1994      67
1995     190
1996     557
1997     501
1998     492
1999     643
2000     474
2001     426
2002     563
2003     514
2004     510
2005     547
2006     338
2007    1079
2008     865
2009    1379
2010     545
2011     495
2012     711
2013     826
2014     826
2015    1229
2016     759
2017     731
2018     856
2019     546
2020     467
2021     742
2022     600
2023     483
2024    1304
2025     383
Name: count, dtype: int64

We can see Sparse, scattered early records from 1705 to around 1950.

A small rise in the late 1950s–1960s.

A huge jump in 1970 and then stable, dense data from 1980 onward.

There is a massive recorder boom in the 2000s–2020s, likely from citizen science contributions.